apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kubernetestest
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kubernetestest
    spec:
      containers:
      - name: kubernetestest
        image: modelmanagement2.azurecr.io/dundeedatascience
        ports:
        - containerPort: 5071
          name: dockerport
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetestest
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: dockerport
    protocol: TCP
  selector:
    app: kubernetestest
