apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: production_diabetes
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: production_diabetes
    spec:
      containers:
      - name: production_diabetes
        image: devopsml.azurecr.io/diabetes:v1
        ports:
        - containerPort: 5071
          name: dockerport
---
apiVersion: v1
kind: Service
metadata:
  name: production_diabetes
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: dockerport
    protocol: TCP
  selector:
    app: production_diabetes
